# Generated by Django 5.0.14 on 2025-04-20 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(max_length=250, null=True)),
                ('nit', models.CharField(max_length=40, unique=True)),
                ('country', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=20, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('contact_name', models.CharField(max_length=100, null=True)),
                ('contact_phone', models.CharField(max_length=20, null=True)),
                ('contact_email', models.CharField(max_length=200, null=True)),
                ('notes', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='License_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('support_level', models.CharField(max_length=50)),
                ('duration_days', models.PositiveIntegerField()),
                ('max_users', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'License_type',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Module',
            },
        ),
        migrations.CreateModel(
            name='Permission_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('level', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Permission_level',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('codeService', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Company_license_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overage_allowed', models.BooleanField(default=False)),
                ('overage_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('end_date', models.DateField(null=True)),
                ('payment_reference', models.CharField(max_length=100, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('observations', models.CharField(max_length=200, null=True)),
                ('user_limit', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.company')),
            ],
            options={
                'db_table': 'Company_license_detail',
            },
        ),
        migrations.CreateModel(
            name='License_type_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_records', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField()),
                ('custom_limit_note', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.license_type')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.services')),
            ],
            options={
                'db_table': 'License_type_services',
            },
        ),
        migrations.CreateModel(
            name='Detail_license_type_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_limit', models.PositiveIntegerField()),
                ('used_limit', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='registros', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('company_license_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.company_license_detail')),
                ('license_type_services', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.license_type_services')),
            ],
            options={
                'db_table': 'Detail_license_type_services',
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('system_defined', models.BooleanField(default=False)),
                ('logical_route', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.module')),
            ],
            options={
                'db_table': 'Permit',
            },
        ),
        migrations.CreateModel(
            name='Permission_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.groups')),
                ('permission_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.permission_level')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.permit')),
            ],
            options={
                'db_table': 'Permission_group',
            },
        ),
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.company')),
            ],
            options={
                'db_table': 'Spaces',
            },
        ),
        migrations.AddField(
            model_name='permit',
            name='spaces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.spaces'),
        ),
        migrations.AddField(
            model_name='groups',
            name='spaces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.spaces'),
        ),
        migrations.CreateModel(
            name='System_users',
            fields=[
                ('id', models.UUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('spaces', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.spaces')),
            ],
            options={
                'db_table': 'System_users',
            },
        ),
        migrations.CreateModel(
            name='Permission_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('permission_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.permission_level')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.permit')),
                ('system_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.system_users')),
            ],
            options={
                'db_table': 'Permission_user',
            },
        ),
        migrations.CreateModel(
            name='User_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.groups')),
                ('system_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.system_users')),
            ],
            options={
                'db_table': 'User_groups',
            },
        ),
    ]
