# Generated by Django 5.0.14 on 2025-04-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Infrastructure', '0001_initial'),
    ]

    operations = [
    ]
