# Generated by Django 5.0.14 on 2025-04-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='system_users',
            table=None,
        ),
    ]
