# Generated by Django 5.0.14 on 2025-04-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModelBd',
        ),
    ]
