# Generated by Django 5.0.14 on 2025-05-14 03:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infrastructure', '0002_alter_system_users_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_users',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
