# Generated by Django 5.0.14 on 2025-04-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Infrastructure', '0002_auto_20250419_0116'),
    ]

    operations = [
    ]
