# Generated by Django 5.0.14 on 2025-05-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infrastructure', '0003_alter_system_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaces',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
