# Generated by Django 5.0.14 on 2025-04-19 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infrastructure', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='musica',
        ),
        migrations.CreateModel(
            name='Company_license_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overage_allowed', models.BooleanField(default=False)),
                ('overage_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('end_date', models.DateField(null=True)),
                ('payment_reference', models.CharField(max_length=100, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('observations', models.CharField(max_length=200, null=True)),
                ('user_limit', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.company')),
            ],
        ),
    ]
