# Generated by Django 5.0.14 on 2025-05-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infrastructure', '0004_alter_spaces_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='codeService',
            field=models.CharField(max_length=200),
        ),
    ]
