# Generated by Django 5.0.14 on 2025-04-19 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infrastructure', '0005_remove_company_musica_company_license_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='License_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('support_level', models.CharField(max_length=50)),
                ('duration_days', models.PositiveIntegerField()),
                ('max_users', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('codeService', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='License_type_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_records', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField()),
                ('custom_limit_note', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.license_type')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.services')),
            ],
        ),
    ]
