# Generated by Django 5.0.14 on 2025-05-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infrastructure', '0005_alter_services_codeservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
