# Generated by Django 5.0.14 on 2025-04-19 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infrastructure', '0006_license_type_services_license_type_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('level', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail_license_type_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_limit', models.PositiveIntegerField()),
                ('used_limit', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='registros', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('company_license_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.company_license_detail')),
                ('license_type_services', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.license_type_services')),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('system_defined', models.BooleanField(default=False)),
                ('logical_route', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.module')),
            ],
        ),
        migrations.CreateModel(
            name='Permission_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.groups')),
                ('permission_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.permission_level')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.permit')),
            ],
        ),
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.company')),
            ],
        ),
        migrations.AddField(
            model_name='permit',
            name='spaces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.spaces'),
        ),
        migrations.AddField(
            model_name='groups',
            name='spaces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.spaces'),
        ),
        migrations.CreateModel(
            name='System_users',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('spaces', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.spaces')),
            ],
        ),
        migrations.CreateModel(
            name='Permission_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('permission_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.permission_level')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.permit')),
                ('system_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.system_users')),
            ],
        ),
        migrations.CreateModel(
            name='User_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.groups')),
                ('system_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Infrastructure.system_users')),
            ],
        ),
    ]
